model_list:
  # チャットモデル
  - model_name: qwen2.5-0.5b
    litellm_params:
      model: openai/Qwen/Qwen2.5-0.5B-Instruct
      api_base: http://vllm-qwen:8000/v1
      api_key: dummy

  # 埋め込みモデル
  - model_name: multilingual-e5-large
    litellm_params:
      model: huggingface/intfloat/multilingual-e5-large-instruct
      api_base: http://embedding:80
      api_key: dummy

litellm_settings:
  set_verbose: true
  request_timeout: 600
