model_list:
  - model_name: qwen2.5-0.5b
    litellm_params:
      model: openai/qwen2.5-0.5b-instruct
      api_base: http://llama-cpp:8000/v1
      api_key: dummy

  - model_name: multilingual-e5-large
    litellm_params:
      model: huggingface/intfloat/multilingual-e5-large-instruct
      api_base: http://embedding:80
      api_key: dummy

litellm_settings:
  set_verbose: true
  request_timeout: 600
  drop_params: true
